# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
stages: 

  - stage: Build 

    displayName: 'Build' 

    jobs: 

      - job: BuildDEV 

        pool: 

          vmImage: 'windows-latest' 

        steps:

        - task: DotNetCoreCLI@2 

          displayName: 'Restore Packages' 

          inputs: 

            command: restore 

            projects: '**/*.sln' 

        - task: DotNetCoreCLI@2 

          displayName: 'Build WebApp' 

          inputs: 

            command: build 

            projects: '**/*.sln' 

            arguments: '--configuration Debug' 

            workingDirectory: '$(System.DefaultWorkingDirectory)' 

        - task: DotNetCoreCLI@2 

          displayName: 'Create Package' 

          inputs: 

            command: publish 

            projects: '**/*.sln' 

            arguments: '--configuration Debug --output $(Build.ArtifactStagingDirectory)' 

            zipAfterPublish: true 

            publishWebProjects: true 

        - task: PublishBuildArtifacts@1 

          displayName: 'Publish Package' 

          inputs: 

            PathtoPublish: '$(Build.ArtifactStagingDirectory)' 

            ArtifactName: 'TailSpin' 

        - task: DotNetCoreCLI@2 

          displayName: 'Test Package' 

          inputs: 

            command: test 

            projects: '**/*.sln' 

            arguments: '--configuration Debug' 

  - stage: DeployDEV 

    displayName: 'Deploy Development' 
    jobs: 

      - deployment: Deploy 

        displayName: 'Deploy Development' 

        pool: 

          vmImage: 'windows-latest' 

  

        environment: 'Development' 
          
        strategy: 

            runOnce: 

              deploy: 

                steps: 
                - checkout: self 

                - task: AzureResourceManagerTemplateDeployment@3 

                  displayName: 'Deploy Infrastructure' 

                  inputs: 

                    deploymentScope: 'Resource Group' 

                    azureResourceManagerConnection: 'splan-tailspin-RommelS-dev' 

                    subscriptionId: '0e45013a-4947-4c07-8008-63623120a0bd' 

                    action: 'Create Or Update Resource Group' 

                    resourceGroupName: 'DevOpsDay' 

                    location: 'Australia East' 

                    templateLocation: 'Linked artifact' 

                    csmFile: '$(Build.SourcesDirectory)/ARMTemplates/azuredeploy.json' 

                    csmParametersFile: '$(Build.SourcesDirectory)/ ARMTemplates/azuredeploy.parameters.dev.json' 

                    deploymentMode: 'Incremental' 

                - task: DownloadPipelineArtifact@2 

                  displayName: 'Download Build Artifacts' 

                  inputs: 

                    buildType: 'current' 

                    itemPattern:  

                    targetPath: '$(Build.ArtifactStagingDirectory)' 
                - task: AzureRmWebAppDeployment@4 

                  inputs: 

                    ConnectionType: 'AzureRM' 

                    azureSubscription: 'splan-tailspin-RommelS-dev' 

                    appType: 'webApp' 

                    WebAppName: 'webapp-tailspin-RommelS-dev' 

                    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip' 

                
  - stage: DeployQA

    displayName: 'Deploy QA' 
    jobs: 

      - deployment: Deploy 

        displayName: 'Deploy QA' 

        pool: 

          vmImage: 'windows-latest' 

  

        environment: 'QA' 
          
        strategy: 

            runOnce: 

              deploy: 

                steps: 

                - checkout: self 

                - task: AzureResourceManagerTemplateDeployment@3 

                  displayName: 'Deploy Infrastructure' 

                  inputs: 

                    deploymentScope: 'Resource Group' 

                    azureResourceManagerConnection: 'splan-tailspin-RommelS-dev' 

                    subscriptionId: '0e45013a-4947-4c07-8008-63623120a0bd' 

                    action: 'Create Or Update Resource Group' 

                    resourceGroupName: 'DevOpsDay' 

                    location: 'Australia East' 

                    templateLocation: 'Linked artifact' 

                    csmFile: '$(Build.SourcesDirectory)/ARMTemplates/azuredeploy.json' 

                    csmParametersFile: '$(Build.SourcesDirectory)/ ARMTemplates/azuredeploy.parameters.dev.json' 

                    deploymentMode: 'Incremental' 

                - task: DownloadPipelineArtifact@2 

                  displayName: 'Download Build Artifacts' 

                  inputs: 

                    buildType: 'current' 

                    itemPattern:  

                    targetPath: '$(Build.ArtifactStagingDirectory)' 
                - task: AzureRmWebAppDeployment@4 

                  inputs: 

                    ConnectionType: 'AzureRM' 

                    azureSubscription: 'splan-tailspin-RommelS-QA' 

                    appType: 'webApp' 

                    WebAppName: 'webapp-tailspin-RommelS-QA' 

                    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip' 